### ISSUE TITLE
Reply Message not Work

### ISSUE THREAD

**Issue by pabloruan0710** [AragurDEV/yowsup#36]
I 'm trying to reply to a message and it does not return anything to me, can someone reply?

**Comment by AragurDEV** [comment]
So you don't recive the message?
Please describe your issue with more details

**Comment by pabloruan0710** [comment]
@AragurDEV 
When someone responds in a message I sent from yowsup, I can not get this response on yowsup

**Comment by AragurDEV** [comment]
@mikesalmonuk yes same is wrong on my side.
But I don't have time to look at it atm.
Would you mind finxing it? File located at yowsup/layers/axolotl/layer_recive.yp

**Comment by mikesalmonuk** [comment]
Sure, will have a look later today and try fix it. Didn't want to start changing code if you had yours correct and it was my config or something wrong. Will take a look and try figure something out!

**Comment by mikesalmonuk** [comment]
So far I've narrowed it down to an issue here: https://github.com/tgalal/python-axolotl/issues/16
Will keep looking. 
It might be that we need to fork that library too, and make some updates and edits in there.

**Comment by AragurDEV** [comment]
I forked and edited it already

**Comment by mikesalmonuk** [comment]
OK, all working as expected with tags and replies.
You got to `pip install git+git://github.com/AragurDEV/python-axolotl.git` and everything then works as expected with current master yowsup branch.
👍

**Comment by pabloruan0710** [comment]
fixed in commit [#9d651b5](https://github.com/AragurDEV/yowsup/commit/9d651b5fed13f121fc89840e973f036f87aa55c5)

**Comment by AragurDEV** [comment]
@mikesalmonuk can you check setup.py? I think it should already be pulled from GitHub

**Comment by mikesalmonuk** [comment]
@AragurDEV just checked and it's there in setup, so all good. i think i had installed it directly using pip, so running setup meant it was already installed and didn't work as expected, but removed my installation and all good now!

**Comment by AragurDEV** [comment]
Issue still occuring
wiht following issues: "InvalidMessageException Invalid signature!" or "InvalidMessageException 'utf-8' codec can't decode byte 0x8a in position 30: invalid start byte"

**Comment by mikesalmonuk** [comment]
It's fine for me if you mention someone or reply to a text message. But if you reply to an image, I get "xml-incorrectly-formed" or something (cleared the error in my terminal now, but something about bad xml). 
What was your message you replied with (did it contain non standard characters or anything)?

**Comment by AragurDEV** [comment]
I'm replying to my own message 'Test' with 'Test' 
![image](https://user-images.githubusercontent.com/11004008/33761717-5282e5d4-dc0a-11e7-91ed-a80f874d7aae.png)
Returning "InvalidMessageException 'utf-8' codec can't decode byte 0x8a in position 8: invalid start byte"
